### ISSUE TITLE
[ISSUE_TEMPLATE] Needs an update

### ISSUE THREAD

**Issue by rprimus** [LibreMatrix/LibreMatrix#1]
<--

Do not open issue here.

The official issue tracker for LibreMatrix is at:

https://github.com/uBlockOrigin/LibreMatrix-issues/issues

-->

Thu Nov 26 14:13:38 GMT 2020

(See above.)

`.github/ISSUE_TEMPLATE.md`:
1.  Still contains a reference to `uBlockOrigin`.
2.  References incorrect repo `LibreMatrix-issues`.

**Comment by AntonMcClure** [comment]
Fixed with commits 8feba7f and 2e82f95.
